// Auto-generated player data
export const PLAYERS_DATA = [
  {
    "name": "Tomas Holmstrom",
    "position": "Left Wing -- shoots L",
    "birth_date": "Jan 23 1973",
    "birth_place": "Pitea, Sweden",
    "height": "6.00",
    "weight": "198",
    "shoots": "L",
    "draft_info": "- round 10 #257 overall 1994 NHL Entry Draft",
    "seasons": [
      {
        "season": "1994-95",
        "team": "Lulea HF",
        "league": "SEL",
        "gp": 40,
        "g": 14,
        "a": 14,
        "pts": 28,
        "pim": 56,
        "plus_minus": "8",
        "playoff_gp": 1,
        "playoff_g": 2,
        "playoff_a": 3,
        "playoff_pts": 20,
        "playoff_pim": 0
      },
      {
        "season": "1995-96",
        "team": "Lulea HF",
        "league": "SEL",
        "gp": 34,
        "g": 12,
        "a": 11,
        "pts": 23,
        "pim": 78,
        "plus_minus": "11",
        "playoff_gp": 6,
        "playoff_g": 2,
        "playoff_a": 8,
        "playoff_pts": 22,
        "playoff_pim": 0
      },
      {
        "season": "1996-97",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 47,
        "g": 6,
        "a": 3,
        "pts": 9,
        "pim": 33,
        "plus_minus": "-10",
        "playoff_gp": 1,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1996-97",
        "team": "Adirondack Red Wings",
        "league": "AHL",
        "gp": 6,
        "g": 3,
        "a": 1,
        "pts": 4,
        "pim": 7,
        "plus_minus": "-1",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1997-98",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 57,
        "g": 5,
        "a": 17,
        "pts": 22,
        "pim": 44,
        "plus_minus": "6",
        "playoff_gp": 22,
        "playoff_g": 7,
        "playoff_a": 12,
        "playoff_pts": 19,
        "playoff_pim": 16
      },
      {
        "season": "1998-99",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 82,
        "g": 13,
        "a": 21,
        "pts": 34,
        "pim": 69,
        "plus_minus": "-11",
        "playoff_gp": 10,
        "playoff_g": 4,
        "playoff_a": 3,
        "playoff_pts": 7,
        "playoff_pim": 4
      },
      {
        "season": "1999-00",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 72,
        "g": 13,
        "a": 22,
        "pts": 35,
        "pim": 43,
        "plus_minus": "4",
        "playoff_gp": 9,
        "playoff_g": 3,
        "playoff_a": 1,
        "playoff_pts": 4,
        "playoff_pim": 16
      },
      {
        "season": "2000-01",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 73,
        "g": 16,
        "a": 24,
        "pts": 40,
        "pim": 40,
        "plus_minus": "-12",
        "playoff_gp": 6,
        "playoff_g": 1,
        "playoff_a": 3,
        "playoff_pts": 4,
        "playoff_pim": 8
      },
      {
        "season": "2001-02",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 69,
        "g": 8,
        "a": 18,
        "pts": 26,
        "pim": 58,
        "plus_minus": "-12",
        "playoff_gp": 23,
        "playoff_g": 8,
        "playoff_a": 3,
        "playoff_pts": 11,
        "playoff_pim": 8
      },
      {
        "season": "2002-03",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 74,
        "g": 20,
        "a": 20,
        "pts": 40,
        "pim": 62,
        "plus_minus": "11",
        "playoff_gp": 4,
        "playoff_g": 1,
        "playoff_a": 1,
        "playoff_pts": 2,
        "playoff_pim": 4
      },
      {
        "season": "2003-04",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 67,
        "g": 15,
        "a": 15,
        "pts": 30,
        "pim": 38,
        "plus_minus": "8",
        "playoff_gp": 12,
        "playoff_g": 2,
        "playoff_a": 2,
        "playoff_pts": 4,
        "playoff_pim": 10
      },
      {
        "season": "2004-05",
        "team": "Lulea HF",
        "league": "SEL",
        "gp": 47,
        "g": 14,
        "a": 16,
        "pts": 30,
        "pim": 50,
        "plus_minus": "-10",
        "playoff_gp": 4,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 18
      },
      {
        "season": "2005-06",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 81,
        "g": 29,
        "a": 30,
        "pts": 59,
        "pim": 66,
        "plus_minus": "14",
        "playoff_gp": 6,
        "playoff_g": 1,
        "playoff_a": 2,
        "playoff_pts": 3,
        "playoff_pim": 12
      },
      {
        "season": "2006-07",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 77,
        "g": 30,
        "a": 22,
        "pts": 52,
        "pim": 58,
        "plus_minus": "13",
        "playoff_gp": 15,
        "playoff_g": 5,
        "playoff_a": 3,
        "playoff_pts": 8,
        "playoff_pim": 14
      },
      {
        "season": "2007-08",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 59,
        "g": 20,
        "a": 20,
        "pts": 40,
        "pim": 58,
        "plus_minus": "9",
        "playoff_gp": 21,
        "playoff_g": 4,
        "playoff_a": 8,
        "playoff_pts": 12,
        "playoff_pim": 26
      },
      {
        "season": "2008-09",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 53,
        "g": 14,
        "a": 23,
        "pts": 37,
        "pim": 38,
        "plus_minus": "18",
        "playoff_gp": 23,
        "playoff_g": 2,
        "playoff_a": 5,
        "playoff_pts": 7,
        "playoff_pim": 22
      },
      {
        "season": "2009-10",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 68,
        "g": 25,
        "a": 20,
        "pts": 45,
        "pim": 60,
        "plus_minus": "5",
        "playoff_gp": 12,
        "playoff_g": 4,
        "playoff_a": 3,
        "playoff_pts": 7,
        "playoff_pim": 12
      },
      {
        "season": "2010-11",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 73,
        "g": 18,
        "a": 19,
        "pts": 37,
        "pim": 62,
        "plus_minus": "-6",
        "playoff_gp": 11,
        "playoff_g": 3,
        "playoff_a": 4,
        "playoff_pts": 7,
        "playoff_pim": 8
      },
      {
        "season": "2011-12",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 74,
        "g": 11,
        "a": 13,
        "pts": 24,
        "pim": 40,
        "plus_minus": "-9",
        "playoff_gp": 5,
        "playoff_g": 1,
        "playoff_a": 1,
        "playoff_pts": 2,
        "playoff_pim": 2
      }
    ]
  },
  {
    "name": "Mickey Redmond",
    "position": "Right Wing -- shoots R",
    "birth_date": "Dec 27 1947",
    "birth_place": "Kirkland Lake, ONT",
    "height": "5.11",
    "weight": "170",
    "shoots": "R",
    "draft_info": null,
    "seasons": [
      {
        "season": "1963-64",
        "team": "Peterborough Petes",
        "league": "OHA",
        "gp": 53,
        "g": 21,
        "a": 17,
        "pts": 38,
        "pim": 0,
        "plus_minus": null,
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1964-65",
        "team": "Peterborough Petes",
        "league": "OHA",
        "gp": 52,
        "g": 23,
        "a": 20,
        "pts": 43,
        "pim": 0,
        "plus_minus": null,
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1965-66",
        "team": "Peterborough Petes",
        "league": "OHA",
        "gp": 48,
        "g": 41,
        "a": 51,
        "pts": 92,
        "pim": 31,
        "plus_minus": null,
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1966-67",
        "team": "Peterborough Petes",
        "league": "OHA",
        "gp": 48,
        "g": 51,
        "a": 44,
        "pts": 95,
        "pim": 44,
        "plus_minus": null,
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1966-67",
        "team": "Houston Apollos",
        "league": "CPHL",
        "gp": 0,
        "g": 0,
        "a": 0,
        "pts": 0,
        "pim": 0,
        "plus_minus": null,
        "playoff_gp": 5,
        "playoff_g": 3,
        "playoff_a": 2,
        "playoff_pts": 5,
        "playoff_pim": 2
      },
      {
        "season": "1967-68",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 41,
        "g": 6,
        "a": 5,
        "pts": 11,
        "pim": 4,
        "plus_minus": "2",
        "playoff_gp": 2,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1967-68",
        "team": "Houston Apollos",
        "league": "CPHL",
        "gp": 15,
        "g": 9,
        "a": 8,
        "pts": 17,
        "pim": 9,
        "plus_minus": null,
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1968-69",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 65,
        "g": 9,
        "a": 15,
        "pts": 24,
        "pim": 12,
        "plus_minus": "14",
        "playoff_gp": 2,
        "playoff_g": 3,
        "playoff_a": 5,
        "playoff_pts": 2,
        "playoff_pim": 0
      },
      {
        "season": "1969-70",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 75,
        "g": 27,
        "a": 27,
        "pts": 54,
        "pim": 61,
        "plus_minus": null,
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1970-71",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 40,
        "g": 14,
        "a": 16,
        "pts": 30,
        "pim": 35,
        "plus_minus": "9",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1970-71",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 21,
        "g": 6,
        "a": 7,
        "pts": 13,
        "pim": 7,
        "plus_minus": "-2",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1971-72",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 78,
        "g": 42,
        "a": 29,
        "pts": 71,
        "pim": 34,
        "plus_minus": "-15",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1972-73",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 76,
        "g": 52,
        "a": 41,
        "pts": 93,
        "pim": 24,
        "plus_minus": "6",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1973-74",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 76,
        "g": 51,
        "a": 26,
        "pts": 77,
        "pim": 14,
        "plus_minus": "-20",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1974-75",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 29,
        "g": 15,
        "a": 12,
        "pts": 27,
        "pim": 18,
        "plus_minus": "-12",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "1975-76",
        "team": "Detroit Red Wings",
        "league": "NHL",
        "gp": 37,
        "g": 11,
        "a": 17,
        "pts": 28,
        "pim": 10,
        "plus_minus": "-17",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      }
    ]
  },
  {
    "name": "Ryan O'Reilly",
    "position": "Center -- shoots L",
    "birth_date": "Feb 7 1991",
    "birth_place": "Clinton, ONT",
    "height": "6.01",
    "weight": "207",
    "shoots": "L",
    "draft_info": "- round 2 #33 overall 2009 NHL Entry Draft",
    "seasons": [
      {
        "season": "2006-07",
        "team": "Toronto Jr. Canadiens",
        "league": "OPJHL",
        "gp": 1,
        "g": 1,
        "a": 0,
        "pts": 1,
        "pim": 0,
        "plus_minus": "0",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2007-08",
        "team": "Erie Otters",
        "league": "OHL",
        "gp": 61,
        "g": 19,
        "a": 33,
        "pts": 52,
        "pim": 14,
        "plus_minus": "-18",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2008-09",
        "team": "Erie Otters",
        "league": "OHL",
        "gp": 68,
        "g": 16,
        "a": 50,
        "pts": 66,
        "pim": 26,
        "plus_minus": "1",
        "playoff_gp": 5,
        "playoff_g": 0,
        "playoff_a": 5,
        "playoff_pts": 5,
        "playoff_pim": 2
      },
      {
        "season": "2009-10",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 81,
        "g": 8,
        "a": 18,
        "pts": 26,
        "pim": 18,
        "plus_minus": "4",
        "playoff_gp": 6,
        "playoff_g": 1,
        "playoff_a": 0,
        "playoff_pts": 1,
        "playoff_pim": 2
      },
      {
        "season": "2010-11",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 74,
        "g": 13,
        "a": 13,
        "pts": 26,
        "pim": 16,
        "plus_minus": "-7",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2011-12",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 81,
        "g": 18,
        "a": 37,
        "pts": 55,
        "pim": 12,
        "plus_minus": "-1",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2012-13",
        "team": "Magnitogorsk Metallurg",
        "league": "KHL",
        "gp": 12,
        "g": 5,
        "a": 5,
        "pts": 10,
        "pim": 2,
        "plus_minus": "6",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2012-13",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 29,
        "g": 6,
        "a": 14,
        "pts": 20,
        "pim": 4,
        "plus_minus": "-3",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2013-14",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 80,
        "g": 28,
        "a": 36,
        "pts": 64,
        "pim": 2,
        "plus_minus": "-1",
        "playoff_gp": 7,
        "playoff_g": 2,
        "playoff_a": 4,
        "playoff_pts": 6,
        "playoff_pim": 0
      },
      {
        "season": "2014-15",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 82,
        "g": 17,
        "a": 38,
        "pts": 55,
        "pim": 12,
        "plus_minus": "-5",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2015-16",
        "team": "Buffalo Sabres",
        "league": "NHL",
        "gp": 71,
        "g": 21,
        "a": 39,
        "pts": 60,
        "pim": 8,
        "plus_minus": "-16",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2016-17",
        "team": "Buffalo Sabres",
        "league": "NHL",
        "gp": 72,
        "g": 20,
        "a": 35,
        "pts": 55,
        "pim": 10,
        "plus_minus": "-1",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2017-18",
        "team": "Buffalo Sabres",
        "league": "NHL",
        "gp": 81,
        "g": 24,
        "a": 37,
        "pts": 61,
        "pim": 2,
        "plus_minus": "-23",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2018-19",
        "team": "St. Louis Blues",
        "league": "NHL",
        "gp": 82,
        "g": 28,
        "a": 49,
        "pts": 77,
        "pim": 12,
        "plus_minus": "22",
        "playoff_gp": 26,
        "playoff_g": 8,
        "playoff_a": 15,
        "playoff_pts": 23,
        "playoff_pim": 4
      },
      {
        "season": "2019-20",
        "team": "St. Louis Blues",
        "league": "NHL",
        "gp": 71,
        "g": 12,
        "a": 49,
        "pts": 61,
        "pim": 10,
        "plus_minus": "11",
        "playoff_gp": 9,
        "playoff_g": 4,
        "playoff_a": 7,
        "playoff_pts": 11,
        "playoff_pim": 0
      },
      {
        "season": "2020-21",
        "team": "St. Louis Blues",
        "league": "NHL",
        "gp": 56,
        "g": 24,
        "a": 30,
        "pts": 54,
        "pim": 18,
        "plus_minus": "26",
        "playoff_gp": 4,
        "playoff_g": 0,
        "playoff_a": 3,
        "playoff_pts": 3,
        "playoff_pim": 2
      },
      {
        "season": "2021-22",
        "team": "St. Louis Blues",
        "league": "NHL",
        "gp": 78,
        "g": 21,
        "a": 37,
        "pts": 58,
        "pim": 12,
        "plus_minus": "11",
        "playoff_gp": 12,
        "playoff_g": 7,
        "playoff_a": 5,
        "playoff_pts": 12,
        "playoff_pim": 2
      },
      {
        "season": "2022-23",
        "team": "St. Louis Blues",
        "league": "NHL",
        "gp": 40,
        "g": 12,
        "a": 7,
        "pts": 19,
        "pim": 10,
        "plus_minus": "-24",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2022-23",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 13,
        "g": 4,
        "a": 7,
        "pts": 11,
        "pim": 6,
        "plus_minus": "3",
        "playoff_gp": 11,
        "playoff_g": 3,
        "playoff_a": 6,
        "playoff_pts": 9,
        "playoff_pim": 5
      },
      {
        "season": "2023-24",
        "team": "Nashville Predators",
        "league": "NHL",
        "gp": 82,
        "g": 26,
        "a": 43,
        "pts": 69,
        "pim": 18,
        "plus_minus": "6",
        "playoff_gp": 6,
        "playoff_g": 1,
        "playoff_a": 1,
        "playoff_pts": 2,
        "playoff_pim": 0
      },
      {
        "season": "2024-25",
        "team": "Nashville Predators",
        "league": "NHL",
        "gp": 79,
        "g": 21,
        "a": 32,
        "pts": 53,
        "pim": 24,
        "plus_minus": "-23",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2025-26",
        "team": "Nashville Predators",
        "league": "NHL",
        "gp": 16,
        "g": 6,
        "a": 4,
        "pts": 10,
        "pim": 0,
        "plus_minus": "-4",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      }
    ]
  },
  {
    "name": "Logan Mailloux",
    "position": "Defense -- shoots R",
    "birth_date": "Apr 15 2003",
    "birth_place": "Belle River, ONT",
    "height": "6.03",
    "weight": "212",
    "shoots": "R",
    "draft_info": "- round 1 #31 overall 2021 NHL Entry Draft",
    "seasons": [
      {
        "season": "2019-20",
        "team": "London Knights",
        "league": "OHL",
        "gp": 4,
        "g": 0,
        "a": 0,
        "pts": 0,
        "pim": 2,
        "plus_minus": "-2",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2019-20",
        "team": "London Nationals",
        "league": "GOJHL",
        "gp": 48,
        "g": 18,
        "a": 51,
        "pts": 69,
        "pim": 94,
        "plus_minus": "5",
        "playoff_gp": 2,
        "playoff_g": 2,
        "playoff_a": 4,
        "playoff_pts": 24,
        "playoff_pim": 0
      },
      {
        "season": "2021-22",
        "team": "London Knights",
        "league": "OHL",
        "gp": 12,
        "g": 3,
        "a": 6,
        "pts": 9,
        "pim": 13,
        "plus_minus": "7",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2022-23",
        "team": "London Knights",
        "league": "OHL",
        "gp": 59,
        "g": 25,
        "a": 28,
        "pts": 53,
        "pim": 77,
        "plus_minus": "15",
        "playoff_gp": 21,
        "playoff_g": 8,
        "playoff_a": 16,
        "playoff_pts": 24,
        "playoff_pim": 45
      },
      {
        "season": "2023-24",
        "team": "Laval Rocket",
        "league": "AHL",
        "gp": 72,
        "g": 14,
        "a": 33,
        "pts": 47,
        "pim": 91,
        "plus_minus": "-8",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2023-24",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 1,
        "g": 0,
        "a": 1,
        "pts": 1,
        "pim": 0,
        "plus_minus": "1",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2024-25",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 7,
        "g": 2,
        "a": 2,
        "pts": 4,
        "pim": 6,
        "plus_minus": "-5",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2024-25",
        "team": "Laval Rocket",
        "league": "AHL",
        "gp": 63,
        "g": 12,
        "a": 21,
        "pts": 33,
        "pim": 74,
        "plus_minus": "5",
        "playoff_gp": 13,
        "playoff_g": 2,
        "playoff_a": 4,
        "playoff_pts": 6,
        "playoff_pim": 28
      },
      {
        "season": "2025-26",
        "team": "St. Louis Blues",
        "league": "NHL",
        "gp": 9,
        "g": 0,
        "a": 0,
        "pts": 0,
        "pim": 4,
        "plus_minus": "-12",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2016-17",
        "team": "Saskatoon Blades",
        "league": "WHL",
        "gp": 19,
        "g": 6,
        "a": 4,
        "pts": 10,
        "pim": 4,
        "plus_minus": "3",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2017-18",
        "team": "Saskatoon Blades",
        "league": "WHL",
        "gp": 52,
        "g": 7,
        "a": 39,
        "pts": 46,
        "pim": 12,
        "plus_minus": "-10",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2018-19",
        "team": "Saskatoon Blades",
        "league": "WHL",
        "gp": 62,
        "g": 25,
        "a": 48,
        "pts": 73,
        "pim": 40,
        "plus_minus": "15",
        "playoff_gp": 10,
        "playoff_g": 5,
        "playoff_a": 3,
        "playoff_pts": 8,
        "playoff_pim": 6
      },
      {
        "season": "2019-20",
        "team": "Rockford IceHogs",
        "league": "AHL",
        "gp": 3,
        "g": 0,
        "a": 0,
        "pts": 0,
        "pim": 0,
        "plus_minus": "-1",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2019-20",
        "team": "Chicago Blackhawks",
        "league": "NHL",
        "gp": 64,
        "g": 8,
        "a": 15,
        "pts": 23,
        "pim": 24,
        "plus_minus": "-1",
        "playoff_gp": 9,
        "playoff_g": 1,
        "playoff_a": 5,
        "playoff_pts": 6,
        "playoff_pim": 4
      },
      {
        "season": "2020-21",
        "team": "Chicago Blackhawks",
        "league": "NHL",
        "gp": 18,
        "g": 2,
        "a": 8,
        "pts": 10,
        "pim": 4,
        "plus_minus": "-3",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2021-22",
        "team": "Chicago Blackhawks",
        "league": "NHL",
        "gp": 70,
        "g": 9,
        "a": 17,
        "pts": 26,
        "pim": 43,
        "plus_minus": "-18",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2022-23",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 58,
        "g": 14,
        "a": 24,
        "pts": 38,
        "pim": 43,
        "plus_minus": "-2",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2023-24",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 2,
        "g": 0,
        "a": 2,
        "pts": 2,
        "pim": 0,
        "plus_minus": "2",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2024-25",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 57,
        "g": 10,
        "a": 12,
        "pts": 22,
        "pim": 40,
        "plus_minus": "-29",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2025-26",
        "team": "Montreal Canadiens",
        "league": "NHL",
        "gp": 11,
        "g": 4,
        "a": 2,
        "pts": 6,
        "pim": 6,
        "plus_minus": "1",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      }
    ]
  },
  {
    "name": "Nazem Kadri",
    "position": "Center -- shoots L",
    "birth_date": "Oct 6 1990",
    "birth_place": "London, ONT",
    "height": "6.00",
    "weight": "185",
    "shoots": "L",
    "draft_info": "- round 1 #7 overall 2009 NHL Entry Draft",
    "seasons": [
      {
        "season": "2006-07",
        "team": "Kitchener Rangers",
        "league": "OHL",
        "gp": 62,
        "g": 7,
        "a": 15,
        "pts": 22,
        "pim": 30,
        "plus_minus": "11",
        "playoff_gp": 9,
        "playoff_g": 0,
        "playoff_a": 2,
        "playoff_pts": 2,
        "playoff_pim": 4
      },
      {
        "season": "2007-08",
        "team": "Kitchener Rangers",
        "league": "OHL",
        "gp": 68,
        "g": 25,
        "a": 40,
        "pts": 65,
        "pim": 57,
        "plus_minus": "9",
        "playoff_gp": 20,
        "playoff_g": 9,
        "playoff_a": 17,
        "playoff_pts": 26,
        "playoff_pim": 26
      },
      {
        "season": "2008-09",
        "team": "London Knights",
        "league": "OHL",
        "gp": 56,
        "g": 25,
        "a": 53,
        "pts": 78,
        "pim": 31,
        "plus_minus": "13",
        "playoff_gp": 14,
        "playoff_g": 9,
        "playoff_a": 12,
        "playoff_pts": 21,
        "playoff_pim": 22
      },
      {
        "season": "2009-10",
        "team": "London Knights",
        "league": "OHL",
        "gp": 56,
        "g": 35,
        "a": 58,
        "pts": 93,
        "pim": 105,
        "plus_minus": "26",
        "playoff_gp": 12,
        "playoff_g": 9,
        "playoff_a": 18,
        "playoff_pts": 27,
        "playoff_pim": 26
      },
      {
        "season": "2009-10",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 1,
        "g": 0,
        "a": 0,
        "pts": 0,
        "pim": 0,
        "plus_minus": "-1",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2010-11",
        "team": "Toronto Marlies",
        "league": "AHL",
        "gp": 44,
        "g": 17,
        "a": 24,
        "pts": 41,
        "pim": 62,
        "plus_minus": "2",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2010-11",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 29,
        "g": 3,
        "a": 9,
        "pts": 12,
        "pim": 8,
        "plus_minus": "-3",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2011-12",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 21,
        "g": 5,
        "a": 2,
        "pts": 7,
        "pim": 8,
        "plus_minus": "2",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2011-12",
        "team": "Toronto Marlies",
        "league": "AHL",
        "gp": 48,
        "g": 18,
        "a": 22,
        "pts": 40,
        "pim": 39,
        "plus_minus": "2",
        "playoff_gp": 11,
        "playoff_g": 3,
        "playoff_a": 7,
        "playoff_pts": 10,
        "playoff_pim": 6
      },
      {
        "season": "2012-13",
        "team": "Toronto Marlies",
        "league": "AHL",
        "gp": 27,
        "g": 8,
        "a": 18,
        "pts": 26,
        "pim": 26,
        "plus_minus": "5",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2012-13",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 48,
        "g": 18,
        "a": 26,
        "pts": 44,
        "pim": 23,
        "plus_minus": "15",
        "playoff_gp": 7,
        "playoff_g": 1,
        "playoff_a": 3,
        "playoff_pts": 4,
        "playoff_pim": 10
      },
      {
        "season": "2013-14",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 78,
        "g": 20,
        "a": 30,
        "pts": 50,
        "pim": 67,
        "plus_minus": "-11",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2014-15",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 73,
        "g": 18,
        "a": 21,
        "pts": 39,
        "pim": 28,
        "plus_minus": "-7",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2015-16",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 76,
        "g": 17,
        "a": 28,
        "pts": 45,
        "pim": 73,
        "plus_minus": "-15",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2016-17",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 82,
        "g": 32,
        "a": 29,
        "pts": 61,
        "pim": 95,
        "plus_minus": "-7",
        "playoff_gp": 6,
        "playoff_g": 1,
        "playoff_a": 1,
        "playoff_pts": 2,
        "playoff_pim": 8
      },
      {
        "season": "2017-18",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 80,
        "g": 32,
        "a": 23,
        "pts": 55,
        "pim": 42,
        "plus_minus": "2",
        "playoff_gp": 4,
        "playoff_g": 0,
        "playoff_a": 2,
        "playoff_pts": 2,
        "playoff_pim": 19
      },
      {
        "season": "2018-19",
        "team": "Toronto Maple Leafs",
        "league": "NHL",
        "gp": 73,
        "g": 16,
        "a": 28,
        "pts": 44,
        "pim": 43,
        "plus_minus": "-2",
        "playoff_gp": 2,
        "playoff_g": 1,
        "playoff_a": 1,
        "playoff_pts": 2,
        "playoff_pim": 19
      },
      {
        "season": "2019-20",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 51,
        "g": 19,
        "a": 17,
        "pts": 36,
        "pim": 97,
        "plus_minus": "7",
        "playoff_gp": 15,
        "playoff_g": 9,
        "playoff_a": 9,
        "playoff_pts": 18,
        "playoff_pim": 10
      },
      {
        "season": "2020-21",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 56,
        "g": 11,
        "a": 21,
        "pts": 32,
        "pim": 34,
        "plus_minus": "-7",
        "playoff_gp": 2,
        "playoff_g": 0,
        "playoff_a": 1,
        "playoff_pts": 1,
        "playoff_pim": 10
      },
      {
        "season": "2021-22",
        "team": "Colorado Avalanche",
        "league": "NHL",
        "gp": 71,
        "g": 28,
        "a": 59,
        "pts": 87,
        "pim": 71,
        "plus_minus": "13",
        "playoff_gp": 16,
        "playoff_g": 7,
        "playoff_a": 8,
        "playoff_pts": 15,
        "playoff_pim": 8
      },
      {
        "season": "2022-23",
        "team": "Calgary Flames",
        "league": "NHL",
        "gp": 82,
        "g": 24,
        "a": 32,
        "pts": 56,
        "pim": 56,
        "plus_minus": "-19",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2023-24",
        "team": "Calgary Flames",
        "league": "NHL",
        "gp": 82,
        "g": 29,
        "a": 46,
        "pts": 75,
        "pim": 43,
        "plus_minus": "0",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2024-25",
        "team": "Calgary Flames",
        "league": "NHL",
        "gp": 82,
        "g": 35,
        "a": 32,
        "pts": 67,
        "pim": 72,
        "plus_minus": "-17",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      },
      {
        "season": "2025-26",
        "team": "Calgary Flames",
        "league": "NHL",
        "gp": 15,
        "g": 4,
        "a": 7,
        "pts": 11,
        "pim": 8,
        "plus_minus": "-6",
        "playoff_gp": 0,
        "playoff_g": 0,
        "playoff_a": 0,
        "playoff_pts": 0,
        "playoff_pim": 0
      }
    ]
  }
];

// Export for use in game.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PLAYERS_DATA;
}
